SNOWFLAKE:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: aws_cas2
      user: dflippo
      role: DFLIPPO_ROLE
      database: DFLIPPO_DEV
      warehouse: DFLIPPO_WH
      schema: DBT_PROJECTS
      threads: 8

