#!/usr/bin/env python3
# /// script
# requires-python = ">=3.9"
# dependencies = []
# ///
"""Install the Snowflake AIM migration plugin for Claude Code.

Clones the plugin from GitHub and installs it to ``.claude/skills/snowflake-migration/``.
Claude Code loads any folder under a skills directory that contains
``.claude-plugin/plugin.json``, so no marketplace or install command is involved. Also
adds two keys to ``.claude/settings.local.json`` to enable the plugin's MCP server and
allow its tools — see :func:`allow_mcp_server`. Re-run to update.

    uv run .claude/setup_migration_plugin.py --dry-run   # preview, change nothing
    uv run .claude/setup_migration_plugin.py             # install or update

Upstream ships only a Cortex Code manifest, so the Claude Code one is generated by
translating it — see :func:`build_manifest` and :func:`translate_hooks`.

Note that the installed plugin's own SessionStart hook installs uv and the scai CLI
system-wide once Claude Code enables it. See
``.claude/skills/snowflake-migration/hooks/install-dependencies.sh``.

Standard library only, so any Python 3.9+ interpreter runs it; ``uv run`` needs no
project or virtualenv. Windows, macOS, Linux.

See .claude/MIGRATION_PLUGIN_SETUP.md for the full explanation.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Any, NoReturn

if TYPE_CHECKING:
    from collections.abc import Sequence

# Must match `requires-python` above. Path.is_relative_to and str.removesuffix set it.
MIN_PYTHON = (3, 9)
if sys.version_info < MIN_PYTHON:  # pragma: no cover - depends on the interpreter
    sys.exit(f"error: Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ is required")

REPO_URL = "https://github.com/Snowflake-Labs/cortex-code-migrations.git"
REPO_SLUG = "Snowflake-Labs/cortex-code-migrations"
DEFAULT_REF = "preview"

PLUGIN_NAME = "snowflake-migration"
HOMEPAGE = (
    "https://docs.snowflake.com/en/migrations/snowconvert-docs/general/"
    "user-guide/snowconvert/migration-skill/skill"
)
MANIFEST_SCHEMA = "https://json.schemastore.org/claude-code-plugin-manifest.json"

# ${CLAUDE_PLUGIN_ROOT} only where it is not already double-quoted.
UNQUOTED_PLUGIN_ROOT = re.compile(r'(?<!")\$\{CLAUDE_PLUGIN_ROOT\}(?!")')

# This script lives in .claude/, so the project root is one level up.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
# Claude Code loads the plugin from here, so this directory must BE the plugin root.
PLUGIN_DIR = PROJECT_ROOT / ".claude" / "skills" / PLUGIN_NAME
SETTINGS_PATH = PROJECT_ROOT / ".claude" / "settings.local.json"
# How Claude Code names this plugin's MCP server in each settings key.
MCP_SERVER_ID = f"plugin:{PLUGIN_NAME}:mcp"
# A rule naming a server, with no tool suffix, allows every tool on that server.
MCP_PERMISSION = f"mcp__plugin_{PLUGIN_NAME}_mcp"

COPY_EXCLUDES = shutil.ignore_patterns("logs", ".git", ".gitignore")

LOGGER = logging.getLogger("setup_migration_plugin")


class ProblemLabelFormatter(logging.Formatter):
    """Label warnings and errors; pass ordinary status lines through unchanged."""

    def format(self, record: logging.LogRecord) -> str:
        """Prefix the message with its level name only when it reports a problem."""
        if record.levelno >= logging.WARNING:
            return f"{record.levelname.lower()}: {record.getMessage()}"
        return record.getMessage()


def configure_logging() -> None:
    """Send status to stdout and problems to stderr."""
    to_stdout = logging.StreamHandler(sys.stdout)
    to_stdout.addFilter(lambda record: record.levelno < logging.WARNING)
    to_stderr = logging.StreamHandler(sys.stderr)
    to_stderr.setLevel(logging.WARNING)

    for handler in (to_stdout, to_stderr):
        handler.setFormatter(ProblemLabelFormatter())
        LOGGER.addHandler(handler)
    LOGGER.setLevel(logging.INFO)


def die(text: str) -> NoReturn:
    """Log an error and exit non-zero."""
    LOGGER.error(text)
    raise SystemExit(1)


def relative(path: Path) -> str:
    """Render *path* relative to the project root when it lies inside it."""
    if path.is_relative_to(PROJECT_ROOT):
        return str(path.relative_to(PROJECT_ROOT))
    return str(path)


def git(*args: str, failure: str = "", dry_run: bool = False) -> str:
    """Run git in the project root and return its stdout.

    Exits with *failure* if the command fails and *failure* was given; otherwise a
    failure yields an empty string. Arguments are passed as argv, so no shell interprets
    them. Under *dry_run* the command is printed instead of run.
    """
    if dry_run:
        shown = [relative(Path(a)) if str(PROJECT_ROOT) in a else a for a in args]
        LOGGER.info(f"would run: git {' '.join(shown)}")
        return ""

    try:
        result = (
            subprocess.run(  # noqa: S603  # fixed argv, no shell, no untrusted input
                [
                    "git",
                    *args,
                ],  # noqa: S607  # resolved from PATH so git shims keep working
                cwd=PROJECT_ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
        )
    except OSError as exc:
        die(f"could not run git: {exc}")

    if result.returncode != 0 and failure:
        detail = (result.stderr or "").strip()
        die(f"{failure}\n  git said: {detail}" if detail else failure)
    return (result.stdout or "").strip()


def installed_version() -> str:
    """Return the installed plugin's VERSION, or an empty string when absent."""
    version_file = PLUGIN_DIR / "VERSION"
    return (
        version_file.read_text(encoding="utf-8").strip()
        if version_file.is_file()
        else ""
    )


def install_plugin(source: Path, *, dry_run: bool) -> None:
    """Copy *source* onto the plugin root, replaced whole so deleted files do not linger.

    copytree preserves file modes, so the hook scripts keep the executable bit that git
    recorded upstream.
    """
    LOGGER.info("==> Installing plugin")

    if dry_run:
        LOGGER.info(f"would delete {relative(PLUGIN_DIR)}")
        LOGGER.info(f"would copy the cloned plugin to {relative(PLUGIN_DIR)}")
        return

    if not (source / ".cortex-plugin" / "plugin.json").is_file():
        die(f"{source} is not the migration plugin (no .cortex-plugin/plugin.json)")

    shutil.rmtree(PLUGIN_DIR, ignore_errors=True)
    shutil.copytree(source, PLUGIN_DIR, ignore=COPY_EXCLUDES)  # creates missing parents
    LOGGER.info(f"installed to {relative(PLUGIN_DIR)}")


def clone_and_install(ref: str, *, dry_run: bool) -> None:
    """Clone the plugin subtree into a temporary directory, then install from it."""
    LOGGER.info(f"==> Cloning {REPO_SLUG} ({ref})")

    with tempfile.TemporaryDirectory() as checkout:
        # Blobless and sparse: only the plugin/ subtree is transferred.
        git(
            "clone",
            "--depth",
            "1",
            "--branch",
            ref,
            "--filter=blob:none",
            "--sparse",
            REPO_URL,
            checkout,
            dry_run=dry_run,
            failure=f"could not clone '{ref}' from {REPO_SLUG} (check network and branch name)",
        )
        git("-C", checkout, "sparse-checkout", "set", "plugin", dry_run=dry_run)
        install_plugin(Path(checkout) / "plugin", dry_run=dry_run)


def translate_hooks(source_hooks: dict[str, Any] | None) -> dict[str, Any]:
    """Port Cortex Code hook config to Claude Code semantics.

    Drops ``matcher``: Cortex accepts ``"*"``, but Claude Code matches SessionStart
    against ``startup|resume|clear|compact``, so ``"*"`` would match nothing and the hook
    would silently never fire. Quotes ``${CLAUDE_PLUGIN_ROOT}`` so a space in the install
    path cannot split the command.
    """
    translated: dict[str, Any] = {}

    for event, entries in (source_hooks or {}).items():
        ported = []
        for entry in entries or []:
            hooks = []
            for hook in entry.get("hooks", []):
                command = hook.get("command")
                if hook.get("type") == "command" and isinstance(command, str):
                    quoted = UNQUOTED_PLUGIN_ROOT.sub(
                        '"${CLAUDE_PLUGIN_ROOT}"', command
                    )
                    hooks.append({**hook, "command": quoted})
                else:
                    hooks.append(hook)
            ported.append(
                {**{k: v for k, v in entry.items() if k != "matcher"}, "hooks": hooks}
            )
        if ported:
            translated[event] = ported

    return translated


def build_manifest(source: dict[str, Any], version: str) -> dict[str, Any]:
    """Translate the Cortex Code manifest *source* into a Claude Code plugin manifest.

    Omits ``skills``: in Claude Code that field names directories to scan for
    ``*/SKILL.md``, so copying upstream's ``["skills/migration"]`` would promote a dozen
    sub-skills to top level. The default scan of ``skills/`` registers just ``migration``,
    which loads the rest on demand. ``commands`` is likewise discovered automatically.

    Adds no provenance key, since ``claude plugin validate --strict`` rejects unknown
    fields; MIGRATION_PLUGIN_SETUP.md records provenance instead.
    """
    manifest: dict[str, Any] = {
        "$schema": MANIFEST_SCHEMA,
        # Carried through unchanged: the plugin's UserPromptSubmit hook injects the
        # literal "snowflake-migration:migration" to name the skill it wants read.
        "name": source.get("name") or PLUGIN_NAME,
        "version": version,
        "description": source.get("description", ""),
        "author": source.get("author") or {"name": "Snowflake"},
        "homepage": HOMEPAGE,
        "repository": REPO_URL.removesuffix(".git"),
    }
    if source.get("mcpServers"):
        manifest["mcpServers"] = source["mcpServers"]
    if hooks := translate_hooks(source.get("hooks")):
        manifest["hooks"] = hooks
    return manifest


def generate_manifest(*, dry_run: bool) -> str:
    """Write the Claude Code manifest into the installed plugin and return its version."""
    LOGGER.info("==> Generating Claude Code manifest")

    cortex_manifest = PLUGIN_DIR / ".cortex-plugin" / "plugin.json"
    output_path = PLUGIN_DIR / ".claude-plugin" / "plugin.json"

    if dry_run:
        LOGGER.info(f"would read {relative(cortex_manifest)}")
        LOGGER.info(f"would write {relative(output_path)}")
        return ""

    try:
        source = json.loads(cortex_manifest.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        die(f"could not read {relative(cortex_manifest)}: {exc}")

    # VERSION is the release of record; the manifest's own copy can lag behind it.
    version = installed_version() or str(source.get("version") or "")
    body = json.dumps(build_manifest(source, version), indent=2, ensure_ascii=False)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    # Path.write_text gained newline= in 3.10, so open() keeps this LF on Windows too.
    with output_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(body + "\n")

    LOGGER.info(f"wrote {relative(output_path)} (version {version or 'unknown'})")
    return version


def allow_mcp_server(*, dry_run: bool) -> None:
    """Enable this plugin's MCP server in .claude/settings.local.json.

    Adds two entries: the server to ``enabledMcpjsonServers``, and a whole-server
    rule to ``permissions.allow``. The rule covers every tool the server exposes,
    so the file stays correct when upstream changes its tool set.

    Keeps all other settings as they are. Drops any per-tool rule for this server,
    because the whole-server rule already covers it.
    """
    LOGGER.info("==> Allowing the MCP server in settings.local.json")

    if dry_run:
        LOGGER.info(f"would update {relative(SETTINGS_PATH)}")
        LOGGER.info(f"  enabledMcpjsonServers += {MCP_SERVER_ID}")
        LOGGER.info(f"  permissions.allow    += {MCP_PERMISSION}")
        return

    settings: dict[str, Any] = {}
    if SETTINGS_PATH.exists():
        try:
            settings = json.loads(SETTINGS_PATH.read_text(encoding="utf-8"))
        except ValueError as exc:
            # Hand-edited file with a syntax error. Report it and change nothing.
            LOGGER.warning(
                f"{relative(SETTINGS_PATH)} is not valid JSON ({exc}); left as is"
            )
            LOGGER.warning(f"Add {MCP_PERMISSION} to permissions.allow by hand.")
            return

    servers = settings.setdefault("enabledMcpjsonServers", [])
    if MCP_SERVER_ID not in servers:
        servers.append(MCP_SERVER_ID)

    permissions = settings.setdefault("permissions", {})
    allow = permissions.setdefault("allow", [])
    # The whole-server rule supersedes any mcp__<server>__<tool> rule for it.
    per_tool_prefix = f"{MCP_PERMISSION}__"
    allow[:] = [rule for rule in allow if not str(rule).startswith(per_tool_prefix)]
    if MCP_PERMISSION not in allow:
        allow.append(MCP_PERMISSION)

    body = json.dumps(settings, indent=2, ensure_ascii=False)
    SETTINGS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with SETTINGS_PATH.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(body + "\n")

    LOGGER.info(f"wrote {relative(SETTINGS_PATH)}")


def report_next_steps(version: str) -> None:
    """Report what to do once the plugin is in place."""
    LOGGER.info(f"==> Setup complete, plugin {PLUGIN_NAME} v{version or '?'}")
    LOGGER.info("1. Restart Claude Code in this directory, or run /reload-plugins.")
    LOGGER.info(f"2. Verify with /plugin, expecting {PLUGIN_NAME}@skills-dir.")
    LOGGER.info("3. Start a migration with /snowflake-migration:migrate.")
    LOGGER.info(
        "On each session start the plugin installs uv and the scai CLI if missing, "
        "then runs scai update. Its MCP server ships inside the scai CLI."
    )


def build_parser() -> argparse.ArgumentParser:
    """Construct the command-line parser."""
    parser = argparse.ArgumentParser(
        description=(
            f"Install the Snowflake AIM migration plugin for Claude Code from {REPO_SLUG} "
            f"into .claude/skills/{PLUGIN_NAME}/, as a skills-directory plugin needing no "
            "marketplace and no settings changes. Re-run to update."
        ),
        epilog="See .claude/MIGRATION_PLUGIN_SETUP.md for the full explanation.",
    )
    parser.add_argument(
        "--ref",
        default=DEFAULT_REF,
        metavar="BRANCH",
        help="upstream branch to track (default: %(default)s; 'main' is the stable release)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print every action that would be taken, without performing any of them",
    )
    return parser


def run(ref: str, *, dry_run: bool) -> int:
    """Install or update the plugin from *ref*."""
    LOGGER.info("==> Checking prerequisites")
    LOGGER.info(f"python {'.'.join(map(str, sys.version_info[:3]))}")

    if shutil.which("git") is None:
        die("git is required. Install it from https://git-scm.com/downloads")
    LOGGER.info(f"git {git('--version').replace('git version ', '')}")

    clone_and_install(ref, dry_run=dry_run)
    version = generate_manifest(dry_run=dry_run)
    allow_mcp_server(dry_run=dry_run)

    if dry_run:
        LOGGER.info("==> Dry run complete, nothing was changed")
        LOGGER.info("Re-run without --dry-run to apply the actions above.")
    else:
        report_next_steps(version)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    """Parse arguments and run."""
    args = build_parser().parse_args(argv)
    configure_logging()
    return run(args.ref, dry_run=args.dry_run)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        raise SystemExit(130) from None
