"""
Migration provenance detection.

Decides whether a project (or a path within it) is mechanically converted
lift-and-shift output rather than hand-authored dbt. That verdict drives tier
suppression: ARCHITECTURE rules are muted for converted code, because a
medallion layout and ``stg_``/``dim_`` naming were never the customer's choice
there, and reporting dozens of naming violations against generated code buries
the findings that matter.

Two things this module deliberately does *not* do:

- **It does not reuse the existing SQL005 header check.** That check
  (``dbt_validation.sql.validator.check_migration_header``) triggers on the bare
  substrings "oracle", "sql server" or "teradata" appearing anywhere in a file,
  then accepts any block comment containing the word "Source" -- matched with
  ``.*?`` under ``re.DOTALL``, so it spans the whole file. It passes vacuously on
  ordinary models and is not a usable provenance signal.

- **It does not treat converted output as a quality reference.** Detecting that
  code was generated by a converter says nothing good about it. Unresolved
  conversion markers, hook-based truncates and per-transformation model
  explosion remain findings; see the MIG and INC packs.

Signals are weighted and require corroboration, because a single weak signal
(one uppercase model name) must not silence the entire architecture pack.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from fnmatch import fnmatch
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dbt_audit.discovery import ProjectContext

# =============================================================================
# Signal patterns
# =============================================================================

#: SnowConvert emits these into generated model SQL. An EWI is an unresolved
#: conversion error; an FDM is a documented functional difference. Either is
#: near-conclusive evidence of machine conversion.
EWI_PATTERN = re.compile(r"SSC-EWI-[A-Z]*\d+", re.IGNORECASE)
FDM_PATTERN = re.compile(r"SSC-FDM-[A-Z]*\d+", re.IGNORECASE)
RESOLVE_EWI_PATTERN = re.compile(r"!!!RESOLVE\s+EWI!!!", re.IGNORECASE)
NEEDS_USER_PATTERN = re.compile(r"--\s*NEEDS-USER:", re.IGNORECASE)

#: The converter names staging models after the ETL source-qualifier instance
#: rather than the source system, so the "source" is literally always "raw".
STG_RAW_PATTERN = re.compile(r"^stg_raw__", re.IGNORECASE)

#: Informatica/SSIS transformation-instance prefixes carried into model names.
ETL_INSTANCE_PATTERN = re.compile(
    r"^(int_)?(SQ|EXP|FIL|LKP|AGG|JNR|RTR|SEQ|UPD|SRT|UNI|NRM|SP|MPLT|TRANS|UPDTRANS)[_\d]",
    re.IGNORECASE,
)

#: The Update Strategy translation threads a DML-decision flag through models.
ETL_CONTROL_COLUMN_PATTERN = re.compile(r"\betl_dml_operation__\b", re.IGNORECASE)

#: Informatica DD_* update-strategy constants appearing as string literals.
DD_CONSTANT_PATTERN = re.compile(r"'DD_(INSERT|UPDATE|DELETE|REJECT)'", re.IGNORECASE)

#: The generated per-data-flow output layout.
ETL_LAYOUT_PATTERN = re.compile(r"(^|/)Output/ETL/", re.IGNORECASE)

#: Placeholder values the converter ships; a project containing these cannot build.
PLACEHOLDER_VALUES = {
    "YOUR_PROJECT_NAME",
    "YOUR_PROFILE_NAME",
    "your_project_name",
    "your_profile_name",
    "YOUR_DB",
    "YOUR_SCHEMA",
}

#: Scaffolding tag the stabilization tooling applies to generated test artifacts.
STABILIZATION_TAG_PATTERN = re.compile(r"stabilization_test", re.IGNORECASE)


# =============================================================================
# Verdict
# =============================================================================


@dataclass
class ProvenanceVerdict:
    """
    Whether a project is converted output, with the evidence that decided it.

    ``score`` accumulates signal weights; ``is_migration`` is the thresholded
    verdict. Keeping the individual signals means the report can justify the
    suppression rather than asserting it, which matters when a customer
    disagrees with the classification.
    """

    is_migration: bool = False
    forced: bool = False
    score: int = 0
    confidence: str = "none"  # none | low | medium | high
    signals: list[str] = field(default_factory=list)
    source_platform: str = ""
    #: Relative paths of models carrying conversion markers.
    migrated_files: set[str] = field(default_factory=set)

    def suppression_reason(self) -> str:
        if self.forced:
            return "migration mode forced via .dbt-audit.yml"
        return "lift-and-shift provenance detected: " + "; ".join(self.signals[:3])

    def covers(self, relative_path: str) -> bool:
        """
        Whether architecture suppression applies to a specific file.

        When the whole project reads as converted, everything is covered. When
        only some files carry markers -- a hybrid repo with migrated legacy
        models beside hand-written marts -- only those paths are suppressed, so
        native code is still held to the full standard.
        """
        if not self.is_migration:
            return False
        if self.forced or self.confidence == "high":
            return True
        return relative_path in self.migrated_files


#: Signal weight -> description. 4 is conclusive on its own; 2 needs a partner.
_THRESHOLD = 4


def classify(project: ProjectContext) -> ProvenanceVerdict:
    """Classify one project's provenance from its files and config."""
    verdict = ProvenanceVerdict()
    config = project.config

    # --- explicit override -------------------------------------------------
    if config.migration_mode == "lift_and_shift":
        verdict.is_migration = True
        verdict.forced = True
        verdict.confidence = "high"
        verdict.score = 99
        verdict.signals.append("migration.mode set to lift_and_shift")
        return verdict
    if config.migration_mode == "native":
        verdict.signals.append(
            "migration.mode set to native; provenance detection skipped"
        )
        return verdict

    for pattern in config.migration_paths:
        for model in project.models:
            if fnmatch(model.relative_path, pattern):
                verdict.migrated_files.add(model.relative_path)
    if verdict.migrated_files:
        verdict.score += 4
        verdict.signals.append(
            f"{len(verdict.migrated_files)} model(s) matched migration.paths in .dbt-audit.yml"
        )

    # --- SCAI project marker ----------------------------------------------
    if (project.root / ".scai" / "config" / "project.yml").is_file():
        verdict.score += 4
        verdict.signals.append(
            ".scai/config/project.yml present (conversion project root)"
        )

    # --- generated output layout ------------------------------------------
    if ETL_LAYOUT_PATTERN.search(project.relative_root.replace("\\", "/")):
        verdict.score += 3
        verdict.signals.append(
            "project sits under an Output/ETL/{Package}/{DataFlow} layout"
        )

    # --- conversion markers in model SQL ----------------------------------
    ewi_files: set[str] = set()
    control_column_files: set[str] = set()
    for model in project.models:
        if (
            EWI_PATTERN.search(model.raw)
            or FDM_PATTERN.search(model.raw)
            or RESOLVE_EWI_PATTERN.search(model.raw)
            or NEEDS_USER_PATTERN.search(model.raw)
        ):
            ewi_files.add(model.relative_path)
        if ETL_CONTROL_COLUMN_PATTERN.search(model.raw) or DD_CONSTANT_PATTERN.search(
            model.raw
        ):
            control_column_files.add(model.relative_path)

    if ewi_files:
        verdict.score += 4
        verdict.signals.append(
            f"{len(ewi_files)} model(s) carry SSC-EWI/SSC-FDM conversion markers"
        )
        verdict.migrated_files |= ewi_files
    if control_column_files:
        verdict.score += 3
        verdict.signals.append(
            f"{len(control_column_files)} model(s) use ETL control flags "
            "(etl_dml_operation__ / DD_* constants)"
        )
        verdict.migrated_files |= control_column_files

    # --- generated naming --------------------------------------------------
    stg_raw = [m.relative_path for m in project.models if STG_RAW_PATTERN.match(m.name)]
    if stg_raw:
        verdict.score += 3
        verdict.signals.append(
            f"{len(stg_raw)} model(s) use the generated stg_raw__ prefix"
        )
        verdict.migrated_files |= set(stg_raw)

    etl_named = [
        m.relative_path for m in project.models if ETL_INSTANCE_PATTERN.match(m.name)
    ]
    if etl_named:
        verdict.score += 2
        verdict.signals.append(
            f"{len(etl_named)} model(s) named after ETL transformation instances "
            "(SQ_/EXP_/FIL_/LKP_/UPDTRANS...)"
        )
        verdict.migrated_files |= set(etl_named)

    # --- placeholder config ------------------------------------------------
    project_text = str(project.project_yml)
    if any(placeholder in project_text for placeholder in PLACEHOLDER_VALUES):
        verdict.score += 3
        verdict.signals.append(
            "dbt_project.yml contains unresolved converter placeholders"
        )

    # --- source platform ---------------------------------------------------
    verdict.source_platform = _infer_platform(project)

    # --- verdict -----------------------------------------------------------
    verdict.is_migration = verdict.score >= _THRESHOLD
    if verdict.score >= 7:
        verdict.confidence = "high"
    elif verdict.score >= _THRESHOLD:
        verdict.confidence = "medium"
    elif verdict.score > 0:
        verdict.confidence = "low"

    # A medium verdict from file-level markers only suppresses those files. A
    # high verdict, or one resting on project-wide structure, covers everything.
    if verdict.is_migration and not verdict.migrated_files:
        verdict.confidence = "high"

    return verdict


def _infer_platform(project: ProjectContext) -> str:
    """Name the source platform when a marker family or file extension reveals it."""
    combined = "\n".join(model.raw[:4000] for model in project.models[:60])
    if re.search(r"SSC-(EWI|FDM)-INF", combined, re.IGNORECASE):
        return "Informatica PowerCenter"
    if re.search(r"SSC-(EWI|FDM)-SSIS", combined, re.IGNORECASE):
        return "SQL Server Integration Services"
    if ETL_CONTROL_COLUMN_PATTERN.search(combined) or DD_CONSTANT_PATTERN.search(
        combined
    ):
        return "Informatica PowerCenter"
    return ""
