name: pip_build
on: workflow_dispatch

jobs:
  dbt_job:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Set Python Version
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pip requirements
        run: pip install -U -r requirements.txt

      - name: Run dbt
        env:
          DBT_PROFILES_DIR: ./docker

          # The following can be created as environment variables
          SNOWFLAKE_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_THREADS: ${{ vars.SNOWFLAKE_THREADS }}
          SNOWFLAKE_QUERY_TAG: ${{ vars.SNOWFLAKE_QUERY_TAG }}

          # The private key should be created as a secret
          DBT_ENV_SECRET_PRIVATE_KEY: ${{ secrets.DBT_ENV_SECRET_PRIVATE_KEY }}

        run: |
          dbt deps
          dbt build

      # Upload dbt artifacts for debugging
      - name: Upload dbt artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dbt-artifacts-${{ github.run_number }}
          path: |
            target/
            logs/
          retention-days: 7
